using System;
using System.Collections.Generic;
using System.Reflection;
using System.Runtime.CompilerServices;
using Friflo.Engine.ECS;

namespace Friflo.EcGui;

internal static class MemberUtils
{
	private static readonly Dictionary<MemberPath, MemberPath[]> PathMembers = new Dictionary<MemberPath, MemberPath[]>();

	internal const BindingFlags Flags = BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.FlattenHierarchy;

	private static readonly Dictionary<Type, MemberPath?> SingleRowComponents = CreateSingleRowComponents();

	internal static MemberPath[] GetMembers(MemberPath path)
	{
		if (PathMembers.TryGetValue(path, out MemberPath[] value))
		{
			return value;
		}
		Type declaringType = path.declaringType;
		Type memberType = path.memberType;
		if (memberType.IsArray)
		{
			string fullPath = GetFullPath(path, "Length");
			MemberPath memberPath = MemberPath.Get(declaringType, fullPath);
			MemberPath[] array = new MemberPath[1] { memberPath };
			PathMembers.Add(path, array);
			return array;
		}
		List<MemberPath> list = new List<MemberPath>();
		MemberInfo[] members = memberType.GetMembers(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.FlattenHierarchy);
		foreach (MemberInfo memberInfo in members)
		{
			if (MultiRowComponent.HideMember(memberInfo.CustomAttributes) || memberInfo.Name.StartsWith('_') || memberInfo.Name.Contains('.'))
			{
				continue;
			}
			if (memberInfo is FieldInfo)
			{
				if (!IsAutoGeneratedBackingField(memberInfo.CustomAttributes))
				{
					AddMember(list, path, memberInfo.Name);
				}
			}
			else if (memberInfo is PropertyInfo { CanRead: not false } propertyInfo && propertyInfo.GetIndexParameters().Length == 0)
			{
				AddMember(list, path, propertyInfo.Name);
			}
		}
		value = list.ToArray();
		PathMembers.Add(path, value);
		return value;
	}

	private static void AddMember(List<MemberPath> members, MemberPath path, string name)
	{
		string fullPath = GetFullPath(path, name);
		MemberPath memberPath = MemberPath.Get(path.declaringType, fullPath);
		if ((object)memberPath.getter != null)
		{
			members.Add(memberPath);
		}
	}

	private static string GetFullPath(MemberPath path, string name)
	{
		if (!(path.path == ""))
		{
			return path.path + "." + name;
		}
		return name;
	}

	internal static bool IsAutoGeneratedBackingField(IEnumerable<CustomAttributeData> customAttributes)
	{
		foreach (CustomAttributeData customAttribute in customAttributes)
		{
			if (customAttribute.AttributeType == typeof(CompilerGeneratedAttribute))
			{
				return true;
			}
		}
		return false;
	}

	private static Dictionary<Type, MemberPath?> CreateSingleRowComponents()
	{
		return new Dictionary<Type, MemberPath>
		{
			{
				typeof(Position),
				MemberPath.Get(typeof(Position), "value")
			},
			{
				typeof(Scale3),
				MemberPath.Get(typeof(Scale3), "value")
			},
			{
				typeof(Rotation),
				MemberPath.Get(typeof(Rotation), "value")
			}
		};
	}

	internal static bool IsSingleRowComponent(ComponentType componentType, out MemberPath? memberPath)
	{
		Type type = componentType.Type;
		if (SingleRowComponents.TryGetValue(type, out memberPath))
		{
			return memberPath != null;
		}
		MemberPath[] members = GetMembers(MemberPath.Get(type, ""));
		if (members.Length == 1)
		{
			memberPath = members[0];
			SingleRowComponents.Add(type, memberPath);
			return true;
		}
		SingleRowComponents.Add(type, null);
		memberPath = null;
		return false;
	}

	internal static bool SupportsHistory(Type type)
	{
		if (FieldHistories.globalSampleIndex == 0)
		{
			return false;
		}
		if (type.IsEnum)
		{
			return true;
		}
		TypeCode typeCode = Type.GetTypeCode(type);
		if ((uint)(typeCode - 3) <= 12u)
		{
			return true;
		}
		return false;
	}

	internal static TypeDrawer GetTypeDrawer(MemberPath memberPath)
	{
		string typeDrawerName = MultiRowComponent.GetTypeDrawerName(memberPath);
		return TypeDrawerUtils.GetTypeDrawer(memberPath.memberType, typeDrawerName);
	}
}
